window.QUIZ_QUESTIONS = [
  {
    id: "easy-1",
    difficulty: "easy",
    category: "Science",
    prompt: "Which planet is known as the Red Planet?",
    options: ["Mars", "Venus", "Jupiter", "Mercury"],
    answer: "Mars",
  },
  {
    id: "easy-2",
    difficulty: "easy",
    category: "Web Basics",
    prompt: "What does HTML stand for?",
    options: [
      "HyperText Markup Language",
      "HighText Machine Language",
      "HyperTransfer Markup Language",
      "Home Tool Markup Language",
    ],
    answer: "HyperText Markup Language",
  },
  {
    id: "easy-3",
    difficulty: "easy",
    category: "Geography",
    prompt: "Which ocean is the largest on Earth?",
    options: ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"],
    answer: "Pacific Ocean",
  },
  {
    id: "easy-4",
    difficulty: "easy",
    category: "JavaScript",
    prompt: "Which JavaScript method converts a JSON string into an object?",
    options: ["JSON.parse()", "JSON.stringify()", "JSON.object()", "JSON.build()"],
    answer: "JSON.parse()",
  },
  {
    id: "easy-5",
    difficulty: "easy",
    category: "Math",
    prompt: "How many minutes are in one hour?",
    options: ["60", "30", "90", "120"],
    answer: "60",
  },
  {
    id: "easy-6",
    difficulty: "easy",
    category: "Computers",
    prompt: "Which component is often called the brain of the computer?",
    options: ["CPU", "Monitor", "Keyboard", "Speaker"],
    answer: "CPU",
  },
  {
    id: "easy-7",
    difficulty: "easy",
    category: "Art",
    prompt: "What color do you get when you mix blue and yellow?",
    options: ["Green", "Purple", "Orange", "Red"],
    answer: "Green",
  },
  {
    id: "easy-8",
    difficulty: "easy",
    category: "Animals",
    prompt: "Which animal is often called the King of the Jungle?",
    options: ["Lion", "Elephant", "Tiger", "Gorilla"],
    answer: "Lion",
  },
  {
    id: "medium-1",
    difficulty: "medium",
    category: "CSS",
    prompt: "Which CSS property controls the space inside an element's border?",
    options: ["padding", "margin", "gap", "outline"],
    answer: "padding",
  },
  {
    id: "medium-2",
    difficulty: "medium",
    category: "HTTP",
    prompt: "Which HTTP status code means Not Found?",
    options: ["404", "200", "500", "301"],
    answer: "404",
  },
  {
    id: "medium-3",
    difficulty: "medium",
    category: "JavaScript",
    prompt: "Which array method creates a new array with only the items that pass a test?",
    options: ["filter()", "map()", "find()", "reduce()"],
    answer: "filter()",
  },
  {
    id: "medium-4",
    difficulty: "medium",
    category: "Geography",
    prompt: "What is the capital city of Australia?",
    options: ["Canberra", "Sydney", "Melbourne", "Perth"],
    answer: "Canberra",
  },
  {
    id: "medium-5",
    difficulty: "medium",
    category: "Biology",
    prompt: "Which gas do plants absorb from the atmosphere?",
    options: ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"],
    answer: "Carbon dioxide",
  },
  {
    id: "medium-6",
    difficulty: "medium",
    category: "Databases",
    prompt: "In SQL, which clause groups rows that share the same value?",
    options: ["GROUP BY", "ORDER BY", "WHERE", "JOIN"],
    answer: "GROUP BY",
  },
  {
    id: "medium-7",
    difficulty: "medium",
    category: "TypeScript",
    prompt: "Which company originally developed TypeScript?",
    options: ["Microsoft", "Google", "Meta", "Oracle"],
    answer: "Microsoft",
  },
  {
    id: "medium-8",
    difficulty: "medium",
    category: "JavaScript",
    prompt: "Which keyword creates a block-scoped variable in JavaScript?",
    options: ["let", "var", "constantly", "static"],
    answer: "let",
  },
  {
    id: "hard-1",
    difficulty: "hard",
    category: "Algorithms",
    prompt: "What is the time complexity of binary search on a sorted array?",
    options: ["O(log n)", "O(n)", "O(n log n)", "O(1)"],
    answer: "O(log n)",
  },
  {
    id: "hard-2",
    difficulty: "hard",
    category: "Web APIs",
    prompt: "Which browser storage API supports large structured data and transactions?",
    options: ["IndexedDB", "sessionStorage", "localStorage", "Cookies"],
    answer: "IndexedDB",
  },
  {
    id: "hard-3",
    difficulty: "hard",
    category: "JavaScript",
    prompt: "What does NaN === NaN evaluate to?",
    options: ["false", "true", "undefined", "0"],
    answer: "false",
  },
  {
    id: "hard-4",
    difficulty: "hard",
    category: "HTTP",
    prompt: "Which HTTP method is typically used to replace an entire resource?",
    options: ["PUT", "PATCH", "POST", "GET"],
    answer: "PUT",
  },
  {
    id: "hard-5",
    difficulty: "hard",
    category: "Databases",
    prompt: "In the ACID properties of databases, what does the I stand for?",
    options: ["Isolation", "Integrity", "Indexing", "Inheritance"],
    answer: "Isolation",
  },
  {
    id: "hard-6",
    difficulty: "hard",
    category: "Astronomy",
    prompt: "Which planet has the shortest day in the solar system?",
    options: ["Jupiter", "Earth", "Saturn", "Mars"],
    answer: "Jupiter",
  },
  {
    id: "hard-7",
    difficulty: "hard",
    category: "React",
    prompt: "Which React hook is commonly used to share data without prop drilling?",
    options: ["useContext", "useMemo", "useRef", "useId"],
    answer: "useContext",
  },
  {
    id: "hard-8",
    difficulty: "hard",
    category: "CSS",
    prompt: "Which selector type carries the highest specificity by itself?",
    options: ["ID selector", "Class selector", "Element selector", "Universal selector"],
    answer: "ID selector",
  },
];
